
on:
  push:
    branches: ["main"]

env:
  NODE_VERSION: '16.20.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: nextjs-as06
        path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: nextjs-as06

    - name: Deploy to Github Pages
      id: deploy-to-github-pages
      uses: actions/deploy-pages@v2
      
  